### PR TITLE
added the ability to support more than one zookeeper instance on the …

### PR DESCRIPTION
**Pull request by ogg1e**
…same server.

We have ZK integration, QA and PreProd on the same server, but using different ports. So I modified this to allow connecting to multiple instances of ZK on the same server. I also added a prefix to the end of the name sent to collectd so you know which environment it belongs in.

### CODE REVIEW

**Comment by mpetazzoni** [comment]
You should use `plugin_instance` to distinguish between the multiple servers, instead of adding a postfix to the name.

**Comment by ogg1e** [comment]
I didn't know it existed. I will add it and update the pull request.

**Comment by wt** [comment]
Sorry. I clicked at just the wrong time.

**Comment by ogg1e** [comment]
I changed it to use plugin_instance instead.

**Comment by ogg1e** [comment]
I added some input parm handling, but that's all I need for my purposes. The master doesn't even have it, so it's an improvement. You should merge this request and add an issue to the master if you want more/better error handling than what I've added.

**Comment by mpetazzoni** [comment]
Cool. Thanks a lot! Could you squash those commits together so it's ready for merge?

**Comment by ogg1e** [comment]
I squashed them together in the last commit.

**Comment by mpetazzoni** [comment]
Hmm, it looks like you messed up your rebase/merge here. Could you take a look?

Also, do you think the `Module`s should be named differently (in the configuration)?

**Comment by ogg1e** [comment]
I'm not extremely experienced with github.... I thought I did it right.

I don't think you can rename the modules differently. I believe they have to have the same name as the Import statement or there's no way to associate it with the python file.

**Comment by mpetazzoni** [comment]
Oh yeah you're right, `Module` in this case in the name of the Python module to be loaded.

I'll take care of the branch cleanup/merge manually.

**Pull request closed without merging**
